# Generated by Django 4.2.22 on 2025-06-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qc_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Login",
        ),
    ]
